### ISSUE TITLE
clone不下来！

### ISSUE THREAD

**Issue by Jack10001** [KimYangOfCat/2021-CSPostgraduate-408#30]
clone了几次都失败了，repository的占用的存储空间太大，建议直接上百度网盘，方便所有fork的同学添加相关资料(百度网盘的链接)！

**Comment by KimYangOfCat** [comment]
> clone了几次都失败了，repository的占用的存储空间太大，建议直接上百度网盘，方便所有fork的同学添加相关资料(百度网盘的链接)！


[`README`](https://github.com/KimYangOfCat/CSPostgraduate-408-2021/blob/master/README.md) 文件中有关于下载的一些方法，也有百度网盘链接，请仔细阅读：

>## 下载：
>
>### 镜像仓库：
>
>本仓库与[ GitLab 上的 CSPostgraduate-408-2021 仓库](https://gitlab.com/Kim.Yang/CSPostgraduate-408-2021) 互为镜像仓库，保持同步更新。
>若因网络问题无法在其一下载，可切换至另一仓库进行尝试
>
>### 下载代理工具
>只需要仓库中收录的个别文件的同学可以直接将该仓库文件的链接拷贝至下载代理工具进行下载，推荐使用的工具有：
>
>+ [GitD](http://gitd.cc/)
>+ [DownGit](https://minhaskamal.github.io/DownGit/#/home) 
>+ [d.serctl](https://d.serctl.com/)
>
>感谢以上所有下载工具的维护者～
>
>### 百毒网盘：
>
>若因网络原因无法下载 Release 与真题中的资源，可点击下方网盘链接下载相应的资源：
>
>> 链接: [https://pan.baidu.com/s/1pa2kQHhsvp9XaJSCS1v-xA](https://pan.baidu.com/s/1pa2kQHhsvp9XaJSCS1v-xA) 提取码: hdqb 
>>
> >若网盘链接失效，可在 issues 中提醒作者更新嗷～


是这个链接失效了吗？

**Comment by Jack10001** [comment]
百度网盘的链接没有失效，下载代理工具好像不是特别给力，gitlab的下载跟github一样，我的意思不能把github当做是百度网盘啊！^_^

**Comment by KimYangOfCat** [comment]
> 百度网盘的链接没有失效，下载代理工具好像不是特别给力，gitlab的下载跟github一样，我的意思不能把github当做是百度网盘啊！^_^

没有失效就好。非常感谢你的建议，经过两个月维护这个仓库的经验，我深刻体验到了你说的不能把GitHub当做百度网盘的原因，依据它的能力，它确实不能有效管理二进制文件。受教了，在以后建立其他仓库时一定会注意这个问题哒。

下载代理工具不太给力，我也没有办法了，只能期望维护他们的大佬能有心情改善使用体验。

并没有把GitHub当百度网盘的意思，当初主要是想放数据结构源码和一些笔记，并希望笔记能编译成静态网页并托管到 GitHub pages，以此提升阅读体验!!（只是后来时间越来越紧，用 markdown 写笔记的速度太慢，就没怎么更新了）。

其他资源只是后来附加的，原本并不打算放在GitHub上，只是个人习惯，怕丢失数据，便想着做个备份，GitLab的同步仓库同样只是为了数据备份。因此造成整个仓库的体积较大，造成 clone 比较困难。对此，个人非常抱歉。但GitHub是一个开放的平台，它的包容允许每个人以自己喜欢的方式去使用它。

为了提升其他朋友的下载体验，我已经尽力提供了许多解决方案（下载代理工具、百度网盘等等），但终究不能解决所有朋友的网络问题，但本质上来说，不能下载是个人的网络问题，终究只能自己去探索一些有效方案去解决。我并不应该为此负责，建立这个仓库的目的只是单纯为了记录我个人的学习过程，上传一些资源也只是为了备份一些对我个人有用的数据，仅此而已！

**Comment by Jack10001** [comment]
我的意思后期如果大家有比较好的资源的话可以上传到这个仓库大家一起用！不过也对，后期考研的时间越来越紧，使用github的同学应该少之又少，祝大家考研顺利，维护的同学以及创建者你们也辛苦了，祝大家都顺利上岸！^_^

**Comment by KimYangOfCat** [comment]
> 我的意思后期如果大家有比较好的资源的话可以上传到这个仓库大家一起用！不过也对，后期考研的时间越来越紧，使用github的同学应该少之又少，祝大家考研顺利，维护的同学以及创建者你们也辛苦了，祝大家都顺利上岸！^_^

嗯嗯，祝愿大家都顺利上岸～
关于一些大家有其他好的资源但是由于网络原因无法上传到这个仓库，其实可以在issues中留下下载链接哒，或者给我发email，我愿意代为上传哒～
